"""add left amount to debt model

Revision ID: 91a06429ceb8
Revises: 879f7d889421
Create Date: 2019-08-13 18:10:48.653235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a06429ceb8'
down_revision = '879f7d889421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt', sa.Column('left_amount', sa.Float(precision=24), nullable=True))
    op.drop_column('debt', 'is_current')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt', sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('debt', 'left_amount')
    # ### end Alembic commands ###
